---
- name: kafka
  hosts: master
  gather_facts: no

  vars:
    ansible_become_pass: "ccma"

  tasks:
    - name: Copy multiple .yml files to remote 
      copy: 
        src: "{{ item }}"
        dest: "/home/ccma/{{ item }}"
        owner: ccma
        group: ccma
        mode: 0644
      with_items: 
        - kafka-values.yml
        - kafka-pv.yml
        - test-client.yml

    - name: Initialize persistent volumes
      shell: "kubectl create -f kafka-pv.yml"
      environment: 
        KUBECONFIG: /home/ccma/.kube/config

    - name: Add incubator repository 
      shell: "helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator"
      environment:
        KUBECONFIG: /home/ccma/.kube/config
      register: add_incubator

    - name: Debug add_incubator
      debug: 
        var: add_incubator

    - name: Install Kafka by Helm
      shell: "helm install --name kafka -f kafka-values.yml incubator/kafka"
      environment:
        KUBECONFIG: /home/ccma/.kube/config
      register: install_kafka

    - name: Debug install_kafka
      debug:
        var: install_kafka
       
    - name: Connect to Kafka using a simple Pod
      shell: "kubectl create -f test-client.yml"
      environment:
        KUBECONFIG: /home/ccma/.kube/config
