---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: kafka-data-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: local-storage
  hostPath:
    path: /tmp/data/kafka-data-1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: kafka-data-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: local-storage
  hostPath:
    path: /tmp/data/kafka-data-2
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: kafka-data-3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: local-storage
  hostPath:
    path: /tmp/data/kafka-data-3
  persistentVolumeReclaimPolicy: Retain
